# Generated by Django 4.0 on 2024-07-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_address_number_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
